"""Node 2 — Clarification.

Generates follow-up questions based on user-selected places and preferences.
Uses Qwen LLM when available, falling back to rule-based questions.
"""

import json
import logging

from app.agent.state import AgentState
from app.config import get_settings
from app.services.source_registry import build_source_status

logger = logging.getLogger(__name__)

CLARIFY_SYSTEM = """You are a travel agent for DragonAtlas3D, specializing in Wuhan city trips.

The user has selected some places on the map. Your job is to ask 1-3 clarifying questions
to better understand their travel needs before building an itinerary.

Rules:
- Ask concise, actionable questions in Chinese.
- Each question must have 2-4 concrete options.
- Cover: trip rhythm, missing interest categories, group type, budget level.
- Return ONLY valid JSON with this exact shape:
{"questions": [{"id": "...", "label": "...", "options": ["...", "..."]}]}
"""


def _add_source_status(state: dict, source_id: str, label: str, status: str, note: str, error: str = "") -> None:
    state.setdefault("source_status", [])
    state["source_status"].append(
        build_source_status(
            source_id=source_id,
            source_label=label,
            status=status,
            coverage_note=note,
            provenance="langgraph-agent-node",
            error=error,
        )
    )


def _llm_client():
    """Return a QwenClient if configured, else None."""
    settings = get_settings()
    if not settings.qwen_api_key or not settings.qwen_base_url:
        return None
    from app.services.llm.qwen_client import QwenClient

    return QwenClient(
        api_key=settings.qwen_api_key,
        base_url=settings.qwen_base_url,
        model=settings.qwen_model,
        timeout_seconds=settings.qwen_timeout_seconds,
    )


def _build_clarify_messages(state: AgentState) -> list[dict]:
    nodes_desc = ", ".join(
        f"{n.get('name','')}({n.get('id','')})" for n in state.get("selected_nodes", [])
    )
    return [
        {
            "role": "user",
            "content": (
                f"The user is planning a {state.get('trip_days', 1)}-day trip in {state.get('current_city', 'wuhan')}.\n"
                f"Interest tags: {', '.join(state.get('interest_tags', []))}.\n"
                f"Preference: {state.get('day_or_night_preference', 'balanced')}.\n"
                f"Selected nodes: {nodes_desc or 'none yet'}.\n"
                f"Generate clarifying questions."
            ),
        }
    ]


def _rule_clarify_questions(state: AgentState) -> list[dict]:
    """Fallback rule-based questions when LLM is unavailable."""
    return [
        {
            "id": "trip_days_confirm",
            "label": "您计划在武汉玩几天？",
            "options": ["1", "2", "3"],
        },
        {
            "id": "time_bias",
            "label": "您更喜欢白天还是夜晚的活动节奏？",
            "options": ["day", "night", "balanced"],
        },
        {
            "id": "interest_detail",
            "label": "最感兴趣的方向是？",
            "options": ["景点观光", "美食探店", "街区漫步", "博物馆文化"],
        },
    ]


def clarification(state: AgentState) -> dict:
    """Generate dynamic follow-up questions from the selected nodes and preferences."""
    llm = _llm_client()
    status = "ready"

    if llm:
        try:
            messages = [
                {"role": "system", "content": CLARIFY_SYSTEM},
                *_build_clarify_messages(state),
            ]
            raw = llm.chat(messages, tool_choice="none")
            content = raw.get("content", "")
            parsed = json.loads(content)
            questions = parsed.get("questions", [])
            if questions:
                _add_source_status(state, "travel-clarifier", "Travel Clarifier (Qwen)", "ready",
                                   "Dynamic clarification generated by Qwen.", "")
                return {
                    "follow_up_questions": questions,
                    "source_status": state.get("source_status", []),
                }
        except Exception as exc:
            logger.warning("LLM clarification failed, falling back to rules: %s", exc)
            status = "partial"

    # Fallback to rule-based
    questions = _rule_clarify_questions(state)
    _add_source_status(state, "travel-clarifier", "Travel Clarifier (Rule)", status,
                       "Clarification generated from built-in rules.",
                       "" if status == "ready" else "LLM unavailable — used rule-based fallback.")
    return {
        "follow_up_questions": questions,
        "source_status": state.get("source_status", []),
    }
