"""Node 5 — Explanation.

Generates human-readable reasoning and answer for the itinerary.
Uses Qwen LLM when available, falling back to template-based text.
"""

import json
import logging

from app.agent.state import AgentState
from app.config import get_settings
from app.services.source_registry import build_source_status

logger = logging.getLogger(__name__)

EXPLANATION_SYSTEM = """You are a travel agent explaining a Wuhan itinerary to the user.

Given the itinerary and user preferences, produce:
1. A concise, warm answer paragraph in Chinese explaining the trip plan.
2. A reasoning paragraph explaining WHY the stops are organized this way.

Return ONLY valid JSON:
{"answer": "...", "reasoning": "..."}
"""


def _add_source_status(state: dict, source_id: str, label: str, status: str, note: str, error: str = "") -> None:
    state.setdefault("source_status", [])
    state["source_status"].append(
        build_source_status(
            source_id=source_id,
            source_label=label,
            status=status,
            coverage_note=note,
            provenance="langgraph-agent-node",
            error=error,
        )
    )


def _llm_client():
    """Return a QwenClient if configured, else None."""
    settings = get_settings()
    if not settings.qwen_api_key or not settings.qwen_base_url:
        return None
    from app.services.llm.qwen_client import QwenClient

    return QwenClient(
        api_key=settings.qwen_api_key,
        base_url=settings.qwen_base_url,
        model=settings.qwen_model,
        timeout_seconds=settings.qwen_timeout_seconds,
    )


def _build_explanation_messages(state: AgentState) -> list[dict]:
    return [{
        "role": "user",
        "content": json.dumps({
            "itinerary": state.get("itinerary", {}),
            "preference": state.get("day_or_night_preference", "balanced"),
            "interest_tags": state.get("interest_tags", []),
            "trip_days": state.get("trip_days", 1),
        }, ensure_ascii=False),
    }]


def explanation(state: AgentState) -> dict:
    """Generate human-readable reasoning and answer for the itinerary."""
    itinerary = state.get("itinerary") or {}
    node_names = [n.get("name", "") for n in state.get("selected_nodes", [])]
    pref = state.get("day_or_night_preference", "balanced")

    llm = _llm_client()
    if llm:
        try:
            messages = [
                {"role": "system", "content": EXPLANATION_SYSTEM},
                *_build_explanation_messages(state),
            ]
            raw = llm.chat(messages, tool_choice="none")
            result = json.loads(raw.get("content", "{}"))
            answer = result.get("answer", "")
            reasoning = result.get("reasoning", "")
            if answer:
                _add_source_status(state, "explainer", "Travel Explainer (Qwen)", "ready",
                                   "Explanation generated by Qwen.", "")
                return {
                    "answer": answer,
                    "selected_reasoning": reasoning,
                    "source_status": state.get("source_status", []),
                }
        except Exception as exc:
            logger.warning("LLM explanation failed, falling back to rules: %s", exc)

    # Rule-based fallback
    tag_text = ", ".join(state.get("interest_tags", []))
    rhythm = {"day": "白天为主的游览", "night": "夜晚为主的体验", "balanced": "日夜均衡的节奏"}.get(pref, "均衡的节奏")
    answer = (
        f"为您规划了 {state.get('trip_days', 1)} 天武汉行程，以{', '.join(node_names)}为核心，"
        f"围绕{tag_text or '综合体验'}展开。整体节奏为{rhythm}，同一天的点位尽量就近安排，减少不必要的奔波。"
    )
    reasoning = f"行程基于{len(state.get('selected_nodes', []))}个地图选点，按照您选择的偏好标签和{rhythm}生成。"

    _add_source_status(state, "explainer", "Travel Explainer (Rule)", "ready",
                       "Explanation generated from templates.", "LLM unavailable")
    return {
        "answer": answer,
        "selected_reasoning": reasoning,
        "source_status": state.get("source_status", []),
    }
